[package]
name = "libparagon"
version = "0.1.0"
edition = "2024"
license = "MIT"
repository = "https://github.com/andy-thomason/paragon-of-uncanny-reason"
description = "Async entry points for the Paragon SystemVerilog simulator"

[dependencies]
paragon-of-uncanny-reason = { path = ".." }

[[bin]]
name = "paragon"
path = "src/main.rs"
